version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@0.0.8
jobs:
  build:
    executor:
      name: node/default,
      tag: '10.6'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
  test:
    executor:
      name: node/default,
      tag: '10.6'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
            - run: npm test
    environment:
      CHROME_BIN: "/usr/bin/google-chrome"
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
        only-branch: master
workflows:
  version: 2
  build:
    branches:
      only:
        - dev
        - master
    jobs:
      - build
  test:
    branches:
      only:
        - dev
        - master
    jobs:
      - build
      - test
  deploy:
    branches:
      only:
        - master
    jobs:
      - deploy
