version: 2.1
jobs:
  build:
    branches:
      only:
        - dev
        - master
    docker:
      - image: circleci/node:7.10
    steps:
        - checkout
        - run: npm install
        - run: npm run lint
        - run: npm run build
  test:
    branches:
      only:
        - dev
        - master
    docker:
      - image: circleci/node:7.10-browsers
    environment:
      CHROME_BIN: "/usr/bin/google-chrome"
    steps:
        - checkout
        - run: npm install
        - run: npm test
